import SwiftUI

struct TutorEmptyStateView: View {
    @Environment(\.colorScheme) private var colorScheme
    @Environment(ThemeManager.self) private var themeManager
    @Environment(\.accessibilityReduceMotion) private var reduceMotion
    @State private var isPulsing = false

    let mode: TutorMode
    let onSelectPrompt: (String) -> Void
    let onOpenActions: () -> Void

    var body: some View {
        ScrollView {
            VStack(spacing: AppSpacing.lg) {
                Spacer(minLength: AppSpacing.lg)

                ZStack {
                    Circle()
                        .fill(.thinMaterial)
                        .frame(width: 88, height: 88)
                        .overlay(
                            Circle()
                                .stroke(themeManager.accent.gradient, lineWidth: 1.5)
                                .opacity(0.6)
                        )
                    Image(systemName: mode.icon)
                        .font(.system(size: 32, weight: .medium))
                        .foregroundStyle(themeManager.accent.gradient)
                        .accessibilityHidden(true)
                }
                .scaleEffect(isPulsing ? 1.05 : 1.0)
                .onAppear {
                    guard !reduceMotion else { return }
                    withAnimation(.easeInOut(duration: 2.2).repeatForever(autoreverses: true)) {
                        isPulsing = true
                    }
                }

                VStack(spacing: AppSpacing.xs) {
                    Text(mode.title)
                        .font(.title3.weight(.semibold))
                        .foregroundStyle(AppColor.textPrimary(colorScheme))
                    Text(mode.subtitle)
                        .font(.subheadline)
                        .foregroundStyle(AppColor.textSecondary(colorScheme))
                        .multilineTextAlignment(.center)
                        .padding(.horizontal, AppSpacing.xl)
                }

                Button {
                    onOpenActions()
                } label: {
                    Label("Change mode", systemImage: "square.grid.2x2")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(themeManager.accent.gradient)
                }
                .buttonStyle(.bouncy)
                .accessibilityHint("Opens the Actions menu to pick a different study mode")

                VStack(spacing: AppSpacing.sm) {
                    ForEach(mode.examplePrompts, id: \.self) { prompt in
                        promptChip(text: prompt)
                    }
                }
                .padding(.top, AppSpacing.sm)

                Text("Responses are generated by AI and may contain mistakes. Verify important answers.")
                    .font(.caption)
                    .foregroundStyle(AppColor.textSecondary(colorScheme))
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, AppSpacing.lg)
                    .padding(.top, AppSpacing.sm)

                Spacer(minLength: AppSpacing.xl)
            }
            .padding(AppSpacing.md)
        }
    }

    private func promptChip(text: String) -> some View {
        Button {
            onSelectPrompt(text)
        } label: {
            HStack(spacing: AppSpacing.sm) {
                Text(text)
                    .font(.subheadline.weight(.medium))
                    .foregroundStyle(AppColor.textPrimary(colorScheme))
                Spacer()
                Image(systemName: "arrow.up.right")
                    .font(.caption)
                    .foregroundStyle(AppColor.textSecondary(colorScheme))
            }
            .padding(AppSpacing.md)
            .background(AppColor.backgroundElevated(colorScheme))
            .clipShape(RoundedRectangle(cornerRadius: AppRadius.medium, style: .continuous))
        }
        .buttonStyle(.bouncy)
        .accessibilityLabel(text)
        .accessibilityHint("Sends this example question in \(mode.title) mode")
    }
}

#Preview("Light") {
    TutorEmptyStateView(
        mode: .mathTutor,
        onSelectPrompt: { _ in },
        onOpenActions: {}
    )
    .environment(ThemeManager())
    .preferredColorScheme(.light)
}
